version: '3'

services:
  payload:
    image: node:18-alpine
    container_name: atlas_admin
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    container_name: atlas_mongo
    restart: unless-stopped
    ports:
      # secure this port in prod server. exposed to host for easier dev experience
      - "27017:27017"
    volumes:
      - ./_DATA:/data/db
    environment:
      MONGO_INITDB_DATABASE: atlas_data

volumes:
  node_modules:
